rootProject.name = "taller_3"
include("01.embeddings")
include("02.langchain4j")
include("03.spring-ai")
include("10.spring-prompt")
include("11.spring-rag")
include("12.spring-mcp-client")
include("14.spring-mcp-server-http")
include("13.spring-mcp-server-stdio")
include("16.sprong-correccion")
include("15.spring-memoria")