server:
  port: 8090

app:
  key: xyz
  aimodel: llama3.2

spring:
  ai:
    openai:
      api-key: ${app.key}
      base-url: http://localhost:8080
      chat:
        model: ${app.aimodel}
#
#server:
#  port: 8090
#
#app:
#  key: xyz
#  aimodel: llama-3.1-8b-instant
#  url: https://groq.com
#
#spring:
#  ai:
#    openai:
#      api-key: ${app.key}
#      base-url: ${app.url}
#      chat:
#        model: ${app.aimodel}

logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG
