#server:
#  port: 8090
#
#app:
#  key: xyz
#  aimodel: llama3.2
#
#spring:
#  docker:
#    compose:
#      enabled: true
#      file: 11.spring-rag/docker-compose.yml
#  ai:
#    model:
#      embedding: openai
#    embedding:
#      transformer:
#        onnx:
#          model-uri: classpath:models/model.onnx
##          gpu-device-id: 0
#        tokenizer:
#          uri: classpath:models/tokenizer.json
#    vectorstore:
#      qdrant:
#        collection-name: distri
#    openai:
#      api-key: ${app.key}
#      base-url: http://localhost:8080
#      chat:
#        model: ${app.aimodel}

##server:
##  port: 8090
##
##app:
##  key: xyz
##  aimodel: llama-3.1-8b-instant
##  url: https://groq.com
##
##spring:
##  ai:
##    openai:
##      api-key: ${app.key}
##      base-url: ${app.url}
##      chat:
##        model: ${app.aimodel}
#
#logging:
#  level:
#    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG
server:
  port: 8090

app:
  key: xyz
  aimodel: gemma-4-E4B-it-Q4_K_S.gguf # Nombre exacto que use tu servidor local

spring:
  docker:
    compose:
      enabled: true
      file: 11.spring-rag/docker-compose.yml
  ai:
    model:
      embedding: openai # Deja solo este motor activo
    vectorstore:
      qdrant:
        collection-name: distri
    openai:
      api-key: ${app.key}
      base-url: http://localhost:8080 # Tu servidor local de modelos (LM Studio / Ollama)
      chat:
        model: ${app.aimodel}
      embedding:
        model: all-minilm-l6-v2-q8_0.gguf # Tu modelo de embeddings en el servidor local

logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG
